---
- name: 'Create user'
  hosts: localhost
  become: true
  tasks:
  - name: 'create new user named Theo'
    user:
      name: 'Theo'
      state: present
  - name: "copy files to new user"
    copy:
      src: "~/stunna/user-create.yml"
      dest: "~/zee"
